#!/bin/bash
DOCKERFILE=Dockerfile

echo "Building $CACHE_TAG using build hook!"

echo "Using $DOCKERFILE for build"

docker build \
        --build-arg SERVERLESS_VERSION=1.67.0 \
        -f $DOCKERFILE \
        -t $IMAGE_NAME .
